import { RATE_CARD_META } from './rate-card-meta.mjs';
export { RATE_CARD_META, rateCardStructuredData } from './rate-card-meta.mjs';

export const RATE_CARD = {
  ...RATE_CARD_META,
  introduction: 'Senior product design for startups and established businesses. Choose a focused review, a defined project, or ongoing support.',
  pricingNote: 'All prices are in USD. Starting prices depend on scope. We agree the final scope and price before work begins.',
  contactTitle: 'Tell me what you’re working on',
  contactDescription: 'Email me your goals, timing, and budget. We can work out which engagement fits and what the scope should include.',
  email: 'omar@designedbyomar.com',
  groups: [
    { id: 'audits', title: 'Audits', description: 'Understand what needs attention before committing to a redesign.', services: [
      { id: 'product-audit', name: 'Product Audit', price: '$2,500', timing: 'Approximately 3 business days after access and materials are received.', description: 'A focused expert review of one agreed product flow.', bestFor: 'Teams that need a clear view of usability problems and what to fix first.', includes: 'Expert usability review, prioritized findings, recommended fixes, and a walkthrough.', limits: 'One agreed product flow. Participant research, implementation, and comprehensive accessibility certification are excluded.' },
      { id: 'product-website-audit', name: 'Product + Website Audit', price: 'From $6,500', timing: 'Approximately 1–1.5 weeks after access and materials are received.', description: 'A broader review of how your product and marketing website work together.', bestFor: 'Teams evaluating several journeys alongside their website’s clarity and usability.', includes: 'Review of usability, brand clarity, and accessibility across the agreed surfaces, with prioritized findings and a walkthrough.', limits: 'Up to 3 agreed product flows and 5 agreed marketing pages. Participant research, implementation, and comprehensive accessibility certification are excluded.' },
    ] },
    { id: 'projects', title: 'Projects', description: 'A defined problem, agreed deliverables, and a clear handoff.', services: [
      { id: 'design-sprint', name: 'Design Sprint', price: 'From $12,000', timing: 'Approximately 2 weeks.', description: 'Work through one defined product problem from direction to a testable design.', bestFor: 'Teams that need to resolve a workflow or shape a feature before building.', includes: 'Strategy, workflow, UX architecture, agreed screens and states, a prototype, and handoff.', limits: 'Screen counts and revisions are agreed in the proposal. Participant research and implementation are separately scoped unless explicitly included.' },
      { id: 'design-day', name: 'Design Day', price: '$1,500', timing: '8 hours for a prepared, defined brief.', description: 'A dedicated day of design work on a specific, ready-to-start task.', bestFor: 'Agencies and teams with a small, well-defined need and materials ready.', includes: 'Design work, meetings, revisions, and handoff within the day’s capacity.', limits: 'All work counts toward the 8 hours. Larger or open-ended work needs a separate scope.' },
      { id: 'website-build', name: 'Website Build', price: 'From $18,000', timing: 'Typically 3–4 weeks after content, access, and approvals are ready.', description: 'An agreed marketing website designed and built through launch.', bestFor: 'Businesses that need a new website or a considered rebuild with a defined scope.', includes: 'Strategy, information architecture, UX/UI, development, agreed CMS, analytics, technical SEO foundations, QA, and launch.', limits: 'Templates, integrations, revisions, and content responsibilities are agreed in the proposal. Hosting, subscriptions, and additional copywriting are separately scoped.' },
    ] },
    { id: 'ongoing', title: 'Ongoing support', description: 'Reserved monthly capacity for an agreed set of priorities.', services: [
      { id: 'fractional-40', name: 'Fractional Design — 40 hours', price: '$7,500/month', timing: '40 hours/month; typically around 10 hours/week.', description: 'Senior product design capacity alongside your team.', bestFor: 'Teams needing consistent senior design support on a focused set of priorities.', includes: 'Strategy, UX/UI, workflows, prototypes, and weekly collaboration.', limits: '40 hours total per month, including preparation, meetings, communication, revisions, QA, and handoff. Weekly allocations are indicative.' },
      { id: 'fractional-80', name: 'Fractional Design — 80 hours', price: '$13,500/month', timing: '80 hours/month; typically around 20 hours/week.', description: 'More capacity for product design and collaboration across your team.', bestFor: 'Teams with a larger ongoing roadmap or more research and collaboration needs.', includes: 'Strategy, UX/UI, workflows, prototypes, weekly collaboration, and agreed research and team sessions.', limits: '80 hours total per month, including preparation, meetings, communication, revisions, QA, and handoff. Research recruitment and incentives are separate costs. Weekly allocations are indicative.' },
      { id: 'website-improvement', name: 'Website Improvement', price: '$2,500/month', timing: 'Up to 12 hours/month.', description: 'Reserved time to keep improving an existing website.', bestFor: 'Businesses with regular website updates and a manageable improvement backlog.', includes: 'Website updates, landing pages, CMS work, and agreed analytics or conversion reviews.', limits: '12 hours total per month, including preparation, meetings, communication, revisions, QA, and handoff. Additional work is quoted before it begins.' },
      { id: 'website-design-support', name: 'Website + Design Support', price: '$4,000/month', timing: 'Up to 20 hours/month across website and design work.', description: 'Shared monthly capacity for website improvements and supporting design.', bestFor: 'Businesses needing website work and a steady amount of supporting visual design.', includes: 'Website and design support, including up to 8 static social assets within the monthly capacity.', limits: '20 hours total per month; social assets use that capacity and are not additional hours. Preparation, meetings, communication, revisions, QA, and handoff count toward capacity. Scheduling, video, community management, and copywriting are excluded unless agreed.' },
    ] },
  ],
  terms: [
    { title: 'Payment', text: 'Audits are paid upfront. Projects require 50% at the start and 50% before final delivery. Monthly engagements are paid in advance; fractional design has a two-month minimum.' },
    { title: 'Monthly capacity', text: 'Preparation, meetings, communication, revisions, QA, and handoff count toward monthly capacity. Weekly allocations are indicative; monthly hours are the commitment.' },
    { title: 'Additional work', text: 'Additional work is quoted before it begins.' },
    { title: 'Audit credit', text: 'Design Sprint or Website Build engagements booked within 30 days of audit handoff receive credit equal to 50% of the audit fee, capped at $2,500. The credit is applied to the project total before installments are calculated. Design Days and monthly engagements are excluded.' },
    { title: 'Proposal terms', text: 'Cancellation, unused capacity, refunds, and other contractual terms are settled in the proposal.' },
  ],
};
